apiVersion: v1
kind: Pod
metadata:
  name: nginx-ws
spec:
  containers:
  - name: nginx-webserver
    image: nginx
    ports:
    - containerPort: 80
    env:
        - name: HTML_LOCATION
          value: /app/folder-from-env

