version: '3.8'

volumes:
  pgdata:
    name: pgdata
  volumelagi:
    name: volumelagi

services:
  # definisikan kontainer
  postgres-db:
    container_name: postgres-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=mydb
    volumes:
      - pgdata:/var/lib/postgres/data:volume

  postgres:
    container_name: postgres-db2
    image: postgres
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=mydb
    volumes:
      - volumelagi:/var/lib/postgres/data:volume