version: '3.8'

networks:
  newnet:
    name: newnet
    driver: bridge

services:
  mainapp:
    container_name: mainapp
    image: alpine
    networks:
      - newnet
    depends_on:
      - postgresdb

  postgresdb:
    container_name: postgresdb
    image: postgres
    networks:
      - newnet
    environment:

      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=mydb